name: Workflow with Approval needed

on:
  workflow_dispatch:

jobs:
  needs-approval:
    environment: dev

    runs-on: flyci-macos-large-latest-m1

    steps:
      - name: Use some environment secret when required reviewers for workflow run
        run: "echo The secret ${{ secrets.MY_SECRET }}"

  doesnt-need-approval-refers-env:
    environment: Dev no reviewers
    runs-on: flyci-macos-large-latest-m1

    steps:
      - name: Use some environment var when no approval needed for workflow run
        run: "echo The secret ${{ vars.MY_VAR }}"
  doesnt-need-approval-doesnt-refer-env:
    runs-on: flyci-macos-large-latest-m1

    steps:
      - name: Plain step
        run: "Simple step here."
